/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParamedicalRouteImport } from './routes/paramedical'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AcademyProgramsRouteImport } from './routes/academy-programs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParamedicalSlugRouteImport } from './routes/paramedical.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AcademyProgramsSlugRouteImport } from './routes/academy-programs.$slug'

const ParamedicalRoute = ParamedicalRouteImport.update({
  id: '/paramedical',
  path: '/paramedical',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyProgramsRoute = AcademyProgramsRouteImport.update({
  id: '/academy-programs',
  path: '/academy-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParamedicalSlugRoute = ParamedicalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ParamedicalRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const AcademyProgramsSlugRoute = AcademyProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AcademyProgramsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy-programs': typeof AcademyProgramsRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/experience': typeof ExperienceRoute
  '/paramedical': typeof ParamedicalRouteWithChildren
  '/academy-programs/$slug': typeof AcademyProgramsSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/paramedical/$slug': typeof ParamedicalSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy-programs': typeof AcademyProgramsRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/experience': typeof ExperienceRoute
  '/paramedical': typeof ParamedicalRouteWithChildren
  '/academy-programs/$slug': typeof AcademyProgramsSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/paramedical/$slug': typeof ParamedicalSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy-programs': typeof AcademyProgramsRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/experience': typeof ExperienceRoute
  '/paramedical': typeof ParamedicalRouteWithChildren
  '/academy-programs/$slug': typeof AcademyProgramsSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/paramedical/$slug': typeof ParamedicalSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy-programs'
    | '/contact'
    | '/courses'
    | '/experience'
    | '/paramedical'
    | '/academy-programs/$slug'
    | '/courses/$slug'
    | '/paramedical/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy-programs'
    | '/contact'
    | '/courses'
    | '/experience'
    | '/paramedical'
    | '/academy-programs/$slug'
    | '/courses/$slug'
    | '/paramedical/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy-programs'
    | '/contact'
    | '/courses'
    | '/experience'
    | '/paramedical'
    | '/academy-programs/$slug'
    | '/courses/$slug'
    | '/paramedical/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyProgramsRoute: typeof AcademyProgramsRouteWithChildren
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  ExperienceRoute: typeof ExperienceRoute
  ParamedicalRoute: typeof ParamedicalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/paramedical': {
      id: '/paramedical'
      path: '/paramedical'
      fullPath: '/paramedical'
      preLoaderRoute: typeof ParamedicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy-programs': {
      id: '/academy-programs'
      path: '/academy-programs'
      fullPath: '/academy-programs'
      preLoaderRoute: typeof AcademyProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paramedical/$slug': {
      id: '/paramedical/$slug'
      path: '/$slug'
      fullPath: '/paramedical/$slug'
      preLoaderRoute: typeof ParamedicalSlugRouteImport
      parentRoute: typeof ParamedicalRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/academy-programs/$slug': {
      id: '/academy-programs/$slug'
      path: '/$slug'
      fullPath: '/academy-programs/$slug'
      preLoaderRoute: typeof AcademyProgramsSlugRouteImport
      parentRoute: typeof AcademyProgramsRoute
    }
  }
}

interface AcademyProgramsRouteChildren {
  AcademyProgramsSlugRoute: typeof AcademyProgramsSlugRoute
}

const AcademyProgramsRouteChildren: AcademyProgramsRouteChildren = {
  AcademyProgramsSlugRoute: AcademyProgramsSlugRoute,
}

const AcademyProgramsRouteWithChildren = AcademyProgramsRoute._addFileChildren(
  AcademyProgramsRouteChildren,
)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface ParamedicalRouteChildren {
  ParamedicalSlugRoute: typeof ParamedicalSlugRoute
}

const ParamedicalRouteChildren: ParamedicalRouteChildren = {
  ParamedicalSlugRoute: ParamedicalSlugRoute,
}

const ParamedicalRouteWithChildren = ParamedicalRoute._addFileChildren(
  ParamedicalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyProgramsRoute: AcademyProgramsRouteWithChildren,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  ExperienceRoute: ExperienceRoute,
  ParamedicalRoute: ParamedicalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
